language: node_js
node_js:
  - 8
  - 10
  - 12
  - 14
  - 16

env:
  jobs:
    - CXX=g++ CODECOV_TOKEN="907787fc-d959-4538-9134-a95bdd5de4c1"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++

install:
  - npm install

script:
  - npm test
  - npm run codecov

deploy:
  provider: npm
  email: "sergak.shpak@gmail.com"
  api_key: $NPM_TOKEN
  on:
    branch: master
    tags: true

cache:
  npm: true
  directories:
    - node_modules

notifications:
  email:
    recipients:
      - sergak.shpak@gmail.com
    on_success: never
    on_failure: always
