language: node_js
os:
- linux
dist: bionic
jobs:
  include:
  - node_js: 10
  - node_js: 12
  - node_js: 14
  - node_js: 16
env:
  global:
  - secure: MleXwyhg3xX6sxsQ4SeWaMexoqecOywc+DNYSsUJ3uWkWsGQgT/7Qbt4+mRd8uOxp9AK8PvxYELWdGwK24Mm/SDGGsmjAwXW1vk+w+0RcjThZRh93zxWJSPRRJT8CefFR1GPFjKVHqs+rT8aALO8BKKlTUmX0AuZ7uNlUh0zECXHHGTx+VwoC1nj9zj9hrlj/lsvUThQaTV+EOOPZgiMmymuWJz51DPoeKorOT41aCffcCBbQgG/mWc138WPOt51hbVTMyVYuI5OgzpJTvy3nmruZlBujrGUY9jqg9Sh+fO+KHGcQCGCDxOjF6fpI/2G/1o8IodWeM6anJUgWbOpMrspE3ArhTbRtUpzSYl8RDlB5jJEkGn7zVcvmLGSGPphvgri0Gh06Id01ngXcD0sKYU5G31bk5Y/ROlbjlStwYRopw04A/0ITXV1JMXV/bUMRd/LOw6Sr1I19i1JKtoKzB2nX160WEP8l65nNv/bZzX2i66iZby2FBObaD9TzRa+ymYPKz0mpcxu6wNzxAzq+pGmr/33kOQg4eRREisdyM/Ro+taFB/r+O2mxof2o8Hu2Pjijk+cdQYhvCSN5tjTxzdKHuaspX/Od/EvIS9avW4mx9/1jN8neSQ2E8SgJREOqNTLMaaJwxhn73b29UCzRLXGrB0DDjm5Gcnuh1K6+FQ=
  jobs:
  - CXX=g++ CODECOV_TOKEN="907787fc-d959-4538-9134-a95bdd5de4c1"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++
install:
- npm install
script:
- npm test
- npm run codecov
deploy:
  provider: npm
  email: sergak.shpak@gmail.com
  api_token: "$NPM_API_TOKEN"
  on:
    branch: master
    tags: true
cache:
  npm: true
  directories:
  - node_modules
notifications:
  email:
    recipients:
    - sergak.shpak@gmail.com
    on_success: never
    on_failure: always
